services:
  frontend:
    image: awesome/webapp
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app 
    ports:
      - '5173:5173'
    expose:
      - '5173'
    tty: true
